<?php
/**
 * Implements hook_preprocess().
 */
function octavius_init(){
    global $user;
    drupal_add_js(array('user_js_uid' => $user->uid), 'setting');
}
/**
 * Implements hook_js_alter().
 */
function octavius_js_alter(){
	$settings = octavius_get_settings();
	/**
	 * get all plugin js
	 */
	$paths = array();
	drupal_alter('octavius_plugins', $paths);


	/**
	 * get all admin plugin js
	 */
	$admin_paths = array();
	drupal_alter('octavius_admin_plugins', $admin_paths);

	/**
	 * add core and config if needed
	 */
	if(count($admin_paths)){
		octavius_add_js($settings->url.'/socket.io/socket.io.js',1,'external');
	}
	if(count($paths) || count($admin_paths)){
		octavius_add_js($settings->url.'/files/octavius.core.v1.0.js',2,'external');
		ob_start();
		include 'config.js.php';
		$config_js = ob_get_contents();
		ob_end_clean();
		octavius_add_js($config_js,12,'inline');
	}

	/**
	 * load plugins
	 */
	foreach($paths as $path){
		octavius_add_js($path);
	}
	foreach($admin_paths as $path){
		octavius_add_js($path);
	}
}

function octavius_add_js($js, $weight = 10, $type = 'file'){
	drupal_add_js(
		$js,
	  	array(
			'type' => $type,
			'weight' => $weight,
			'scope' => 'footer',
		)
	);

}

function octavius_octavius_plugins_alter(&$paths){
	$base = drupal_get_path('module','octavius');
	$paths[] = $base.'/js/octavius_escape_admin.js';
}

/**
* Register menus and urls
*/
function octavius_menu() 
{
	return array(
		'admin/config/octavius'=>array(
			'title'=>t('Octavius'),
			'description'=>t('Configure Octavius'),
			'page callback' => 'system_admin_menu_block_page',
		   'file' => 'system.admin.inc',
		   'file path' => drupal_get_path('module', 'system'),
			'access arguments'=>array('setup octavius'),
			'type'=>MENU_NORMAL_ITEM,
		),
		'admin/config/octavius/service'=>array(
			'title'=>t('Service settings'),
			'description'=>t('Configure Octavius service'),
			'page callback'=>'drupal_get_form',
			'page arguments'=>array('octavius_service_settings'),
			'access arguments'=>array('administer octavius'),
			'type'=>MENU_NORMAL_ITEM,
			'weight' => 1,
		),
		'admin/config/octavius/results'=>array(
			'title'=>t('Results'),
			'description'=>t('View results'),
			'page callback'=>'octavius_results_page',
			'access arguments'=>array('results octavius'),
			'type'=>MENU_NORMAL_ITEM,
			'weight' => 2,
		),
	);
}
/**
*	Grant public access
*/
function octavius_public_access()
{
	return true;
}
/**
*	Register octavius permission.
*/
function octavius_permission() {
  return array(
    'administer octavius' => array(
      'title' => t('Octavius sevice settings'),
      'description' => t('Settings for Octavius service'),
    ),
    'setup octavius' => array(
      'title' => t('Octavius module settings'),
      'description' => t('Performance settings for Octavius module'),
    ),
	  'results octavius' => array(
		  'title' => t('Octavius result pages'),
		  'description' => t('All pages that display results from octavius tracking'),
	  ),
  );
}
/**
*	Settings page for octavius service
*/
function octavius_service_settings()
{
	$form=array();
	$settings = octavius_get_settings();
	
	$form['service'] = array(
		'#type'=>'fieldset',
		'#title'=>t('Service settings'),
	);

	$form["service"]['octavius_service_api_key'] = array(
		'#type'=>'textfield',
		'#title'=>t('Api Key'),
		'#default_value' => $settings->api_key,
	);

	$form["service"]['octavius_service_url'] = array(
		'#type'=>'textfield',
		'#title' => t('URL to Octavius service (leave empty for default)'),
		'#default_value' => $settings->url,
	);

	return system_settings_form($form);
	
}

/**
*	Settings page for octavius performance
*/
function octavius_results_page()
{
	// TODO: render octavius results webapp
	return "<p>result</p>";
	
}

/**
 *	Collects all Settings.
 */
function octavius_get_settings()
{
	return (Object) array(
		"api_key" => variable_get("octavius_service_api_key"),
		"url" => variable_get("octavius_service_url", "http://service.octavius.rocks"),
	);
}

/**
 * block for pageviews
 */
function octavius_block_info() {
	$blocks = array();
	$blocks["octavius-pixel"] = array(
		'info' => 'Octavius Pageview Pixel',
		'cache' => DRUPAL_NO_CACHE,
		'status'=>1,
		'region'=>'footer_bottom',
	);
	return $blocks;
}
/**
 * footer block view
 */
function octavius_block_view($delta = '') {
	global $user;
	if($user->uid > 0){
		return;
	}
	$settings = octavius_get_settings();
	if($settings->api_key == "") return;

	$src = $settings->url."/track/".$settings->api_key;
	
	/**
	 * let other plugins alter the query
	 */
	$query = array();
	drupal_alter('octavius_query', $query);

	/**
	 * build key value pairs
	 */
	$all = array();
	foreach ($query as $field => $value) {
		$all[] = $field."=".urlencode($value);
	}

	/**
	 * pixel source addresse
	 */
	$src.= "?".implode("&", $all);

	ob_start();
	?>
	<img style="height: 0px;width: 0px;overflow: hidden;position: absolute;bottom: 0;left: 0;z-index: -10;" src="<?php echo $src; ?>" />
	<?php
	$content = ob_get_contents();
	ob_end_clean();
	return array('content' => $content);
}

/**
 * octavius hook for altering the query for pageview pixel
 * @param  [assoc_array] 	&$query
 */
function octavius_octavius_query_alter(&$query){
	/**
	 * get pagetype
	 */
	$query["pagetype"] = octavius_get_pagetype();

	/**
	 * get content id
	 */
	if ( arg(0) == 'node' && is_numeric(arg(1)) && ! arg(2) ) {
		// node page
		$query['content_id'] = arg(1);
	} else if(arg(0) == "taxonomy" && arg(1) == "term" && is_numeric(arg(2)) && ! arg(3)){
		// taxonomy term page
		$query['content_id'] = arg(2);
	}

	/**
	 * get path
	 */
	$query["url"] = url(current_path());
}

/**
 * look for page type
 * @return [string] name of pagetype
 */
function octavius_get_pagetype(){
	if(drupal_is_front_page()) return "home";
	return arg(0);
}
?>