<?php

/**
* Register menus and urls
*/
function octavius_menu() 
{
	return array(
		'admin/config/octavius'=>array(
			'title'=>t('Octavius'),
			'description'=>t('Configure Octavius'),
			'page callback' => 'system_admin_menu_block_page',
		   'file' => 'system.admin.inc',
		   'file path' => drupal_get_path('module', 'system'),
			'access arguments'=>array('setup octavius'),
			'type'=>MENU_NORMAL_ITEM,
		),
		'admin/config/octavius/service'=>array(
			'title'=>t('Service settings'),
			'description'=>t('Configure Octavius service'),
			'page callback'=>'drupal_get_form',
			'page arguments'=>array('octavius_service_settings'),
			'access arguments'=>array('administer octavius'),
			'type'=>MENU_NORMAL_ITEM,
			'weight' => 1,
		),
		'admin/config/octavius/performance'=>array(
			'title'=>t('Performance settings'),
			'description'=>t('Configure Octavius performance'),
			'page callback'=>'drupal_get_form',
			'page arguments'=>array('octavius_performance_settings'),
			'access arguments'=>array('setup octavius'),
			'type'=>MENU_NORMAL_ITEM,
			'weight' => 2,
		),
		'admin/config/octavius/blacklist'=>array(
			'title'=>t('Blacklists'),
			'description'=>t('Configure Octavius nodes blacklist'),
			'page callback'=>'drupal_get_form',
			'page arguments'=>array('octavius_blacklist'),
			'access arguments'=>array('setup octavius'),
			'type'=>MENU_NORMAL_ITEM,
			'weight' => 3,
		),
		'admin/config/octavius/log'=>array(
			'title'=>t('Log'),
			'description'=>t('Log of newest top lists'),
			'page callback'=>array('octavius_log'),
			'access arguments'=>array('setup octavius'),
			'type'=>MENU_NORMAL_ITEM,
			'weight' => 4,
		),
		'__api/octavius/list' => array(
			'page callback' => 'octavius_url_list',
			'access callback'=>'octavius_public_access',
		),
		'__api/octavius/importer' => array(
			'page callback' => 'octavius_save_data_from_service',
			'access callback'=>'octavius_public_access',
		),				
	);
}
/**
*	Grant public access
*/
function octavius_public_access()
{
	return true;
}
/**
*	Register octavius permission.
*/
function octavius_permission() {
  return array(
    'administer octavius' => array(
      'title' => t('Octavius sevice settings'),
      'description' => t('Settings for Octavius service'),
    ),
    'setup octavius' => array(
      'title' => t('Octavius module settings'),
      'description' => t('Performance settings for Octavius module'),
    ),
  );
}
/**
*	Settings page for octavius service
*/
function octavius_service_settings()
{
	$form=array();
	$settings = octavius_get_settings();
	
	$form['service'] = array(
		'#type'=>'fieldset',
		'#title'=>t('Service settings'),
	);

	$form["service"]['octavius_service_client_name'] = array(
		'#type'=>'textfield',
		'#title'=>t('Client name in service installation'),
		'#default_value' => $settings->client_name,
	);
	// TODO: should be service_client_name in next step
	$form["service"]['octavius_ht_user'] = array(
		'#type'=>'textfield',
		'#title'=>t('User'),
		'#default_value' => $settings->ht_user,
	);
	
	$form["service"]['octavius_ht_passwd'] = array(
		'#type'=>'password',
		'#title' => t('Password'),
	);

	$form["service"]['octavius_service_url'] = array(
		'#type'=>'textfield',
		'#title' => t('URL to Octavius service'),
		'#default_value' => $settings->url,
	);

	return system_settings_form($form);
	
}

/**
*	Settings page for octavius performance
*/
function octavius_performance_settings()
{
	$form=array();
	$settings = octavius_get_settings();

	$form['performance'] = array(
		'#type'=>'fieldset',
		'#title'=>t('Performance settings'),
	);
	$form["performance"]['octavius_page_list_limit'] = array(
		'#type'=>'textfield',
		'#title'=>t('How many Nodes should be delivered on a single Page?'),
		'#default_value' => $settings->page_list_limit,
	);

	return system_settings_form($form);
	
}

/**
*	Settingspage for nodes blacklist that should be ignored for top lists.
*/
function octavius_blacklist()
{
	$form=array();
	$settings = octavius_get_settings();

	$form['blacklist'] = array(
		'#type'=>'fieldset',
		'#title'=>t('Blacklists'),
	);
	$form["blacklist"]['octavius_blacklist_nids'] = array(
		'#type'=>'textarea',
		'#title'=>t('Ignored node ids'),
		'#description' => t('Comma separated list of node ids that are ignored by octavius. Best-practice is to prevent spaces and linebreaks as well.'),
		'#default_value' => $settings->blacklist_nids,
	);
	$types = node_type_get_types();
	$types_array = array();
	foreach ($types as $type => $content_type) {
		$types_array[] = $type;
	}
	$form["blacklist"]['octavius_blacklist_content_types'] = array(
		'#type'=>'textarea',
		'#title'=>t('Ignored content types'),
		'#description' => t('Comma separated list of content types that are ignored by octavius. Best-practice is to prevent spaces and linebreaks as well.<br> Available content types: '.implode(", ", $types_array)),
		'#default_value' => $settings->blacklist_content_types,
	);

	return system_settings_form($form);
	
}

/**
*	Collects all Settings.
*/
function octavius_get_settings()
{	
	// cleanup blacklist
	$blacklist_nids = variable_get("octavius_blacklist_nids");
	$blacklist_nids = str_replace(" ", "", $blacklist_nids);
	$blacklist_nids = str_replace(array("\r","\n"), ",", $blacklist_nids);
	$blacklist_nids = str_replace(array(",,,,",",,,",",,"), ",", $blacklist_nids);
	if(strpos($blacklist_nids, ",") === false){
		$blacklist_nids_array = array();
	} else {
		$blacklist_nids_array = explode(",", $blacklist_nids);
	}

	$blacklist_content_types = variable_get("octavius_blacklist_content_types");
	$blacklist_content_types = str_replace(" ", "", $blacklist_content_types);
	$blacklist_content_types = str_replace(array("\r","\n"), ",", $blacklist_content_types);
	$blacklist_content_types = str_replace(array(",,,,",",,,",",,"), ",", $blacklist_content_types);
	if(strpos($blacklist_content_types, ",") === false){
		$blacklist_content_types_array = array();
	} else {
		$blacklist_content_types_array = explode(",", $blacklist_content_types);
	}

	return (Object) array(
		"page_list_limit" => variable_get("octavius_page_list_limit",1000),
		"ht_passwd" => variable_get("octavius_ht_passwd"),
		"ht_user" => variable_get("octavius_ht_user"),
		"client_name" => variable_get("octavius_service_client_name"),
		"url" => variable_get("octavius_service_url", "http://octavius-dev.palasthotel.de"),
		"blacklist_nids" => $blacklist_nids,
		"blacklist_nids_array" => $blacklist_nids_array,
		"blacklist_content_types" => $blacklist_content_types,
		"blacklist_content_types_array" => $blacklist_content_types_array,
	);
}

/**
*	Get Blacklist as boolean list with nid as keys
*/
function octavius_get_blacklist(){
	$ignored_list = (Object)array("nids" => array(), "content_types" => array() );
	$settings = octavius_get_settings();
	foreach($settings->blacklist_nids_array as $ignored) {
		$ignored_list->nids[$ignored] = true;
	}
	foreach($settings->blacklist_content_types_array as $ignored) {
		$ignored_list->content_types[$ignored] = true;
	}
	return $ignored_list;
}

/**
 * Return JSON formed URL List 
 */
function octavius_url_list($page = null)
{

	// redirect to /1 if no page number is given
	if($page == null) drupal_goto("__api/octavius/list/1", array(), 301);

	$settings = octavius_get_settings();

	global $base_url;
	$root = array();
    $root["pubDate"] = date("D, d M Y H:i:s O");
    $root["lastBuildDate"] = date("D, d M Y H:i:s O");
    
    $root["items"] = array();

    $limit = $settings->page_list_limit;
    $low_limit = ( $page - 1 )  * $limit ;

    $blacklist_cond = array();
    // node ids
    if(count($settings->blacklist_nids_array) > 0){
    	$blacklist_cond[] = "nid NOT IN (".$settings->blacklist_nids.")";
    }
    // content types
    if(count($settings->blacklist_content_types) > 0){
    	$blacklist_cond[] ="type NOT IN('".str_replace(",", "','", $settings->blacklist_content_types)."')";
    }

    $where = "";
    if(count($blacklist_cond) > 0){
    	$where = "WHERE ".implode(" AND ", $blacklist_cond);
    }

	$result = db_query("SELECT n.nid as nid, n.type as type , n.created as created FROM {node} n $where LIMIT $low_limit, $limit");

	foreach ($result as $record) {

		$root["items"][] = array(
			"type" => $record->type,
			"id" => $record->nid,
			"guid" => $base_url."/node/".$record->nid,
			"permalink" => "/".drupal_get_path_alias('node/'.$record->nid),
			"pubDate" => date("Y-m-d H:i:s", $record->created),
		);
	}

    header("Content-Type: application/json;charset=UTF-8");
    echo json_encode($root);
	return;
}

/**
*	Clean octavius tables for newer data.
*/
function octavius_clean_table($type){
	return db_query("TRUNCATE TABLE {octavius_top_list_".$type."}");
}

/**
 * Set Octavius Page Data to Meta Field
*/
function octavius_save_data_from_service() 
{
	$settings = octavius_get_settings();
	// get Latest Date from Octavius
	$path = "/v1.0/".$settings->client_name."/getTopLists";
    $json_result = json_decode(octavius_curl($path), true);
    var_dump($result); 
    foreach ($json_result as $type => $source) {
    	// Get Latest Data from Octavius
    	octavius_clean_table($type);
    	$result = octavius_save_top($type, $source["url"]);
    }
    module_invoke_all('octavius_new_data');
    return;
}

function octavius_save_top($type, $url){

	// Get Latest Data from Octavius
	$json_result = json_decode(octavius_curl($url), true);
	
	// build values
	$values = array();
	foreach ($json_result as $key => $record) {
		$values[] = "('".$record["page_id"]."','".$record["pageviews"]."')";
	}
	if(count($values) > 0 ){
		$values_string = implode(",", $values);
	}
	

	// save values
	return db_query("INSERT INTO {octavius_top_list_".$type."} (nid, views) VALUES $values_string");

}

/**
* Handles curl Requests to Octavius.
* $url: Absolute Path
*/
function octavius_curl($url)
{
	$ch = curl_init ();
	
	$settings = octavius_get_settings();
	$octavius_url = $settings->url;

	// handle missing slashes
	if(substr($octavius_url, -1) == "/" && substr($url, 0, 1) == "/"){
		$octavius_url = substr($settings->url, 0, -1);
	} else if(substr($octavius_url, -1) != "/" && substr($url, 0, 1) != "/"){
		$octavius_url .= "/";
	}

	if($settings->ht_user && $settings->ht_passwd){
		$htaccess = $settings->ht_user.":".$settings->ht_passwd;
		curl_setopt($ch,CURLOPT_USERPWD,$htaccess);
	}
	
    curl_setopt($ch,CURLOPT_URL, $octavius_url.$url);
    curl_setopt($ch,CURLOPT_RETURNTRANSFER,1);
    curl_setopt($ch, CURLOPT_TIMEOUT, 10);

    return curl_exec($ch); 
}

/**
*	Gets top lists by type from database of octavius.
*/
function octavius_get_top($type)
{
	$result = db_query("SELECT * FROM {octavius_top_list_".$type."} ORDER BY views DESC");
	return $result->fetchAll();
}
/**
*	Gets newest local data of the day.
*/
function octavius_get_top_day()
{
	return octavius_get_top("day");
}
/**
*	Gets newest local data of the week.
*/
function octavius_get_top_week()
{
	return octavius_get_top("week");
}
/**
*	Gets newest local data of the month.
*/
function octavius_get_top_month()
{
	return octavius_get_top("month");
}
/**
*	Gets newest local data of the ever.
*/
function octavius_get_top_ever()
{
	return octavius_get_top("ever");
}
/**
*	Renders Data Log page.
*/
function octavius_log(){
	$output = "";
	$day = array();
	foreach (octavius_get_top_day() as $top) {
		$day[] = "<li>Nid: ".$top->nid." -> Pageviews: ".$top->views."</li>";
	}
	if(count($day)>0{
		$output .= "<h2>".t("Top of Yesterday")."<ul>".implode("", $day)."</ul>";
	} else {
		$output .= "<h2>No tops of yesterday</h2>";
	}

	return "<h1>Log:</h1>".$output;
}


?>